### ISSUE TITLE
ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue 

### ISSUE THREAD

**Issue by jongming** [tugkan/aliexpress-scraper#10]
Hello Tugkan,
Just tried the aliexpress-scraper. Ran using the default setting except changed the destination to the United States. Ran the code it ran successfully but zero results. Please see log below.

2020-08-26T04:36:14.420Z ACTOR: Creating Docker container.
2020-08-26T04:36:14.872Z ACTOR: Starting Docker container.
2020-08-26T04:36:16.855Z INFO  System info {"apifyVersion":"0.21.3","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.2"}
2020-08-26T04:36:16.860Z INFO  PHASE -- STARTING ACTOR.
2020-08-26T04:36:16.935Z INFO  ACTOR OPTIONS: --  {"startUrls":[{"url":"https://www.aliexpress.com/category/200003482/dresses.html"}],"language":"en_US","shipTo":"US","currency":"USD","maxItems":1000,"includeDescription":false,"searchInSubcategories":true,"proxy":{"useApifyProxy":false},"extendOutputFunction":"($) => { return {} }","maxFeedbacks":0,"maxQuestions":0}
2020-08-26T04:36:18.519Z INFO  PHASE -- SETTING UP CRAWLER.
2020-08-26T04:36:18.521Z INFO  PHASE -- STARTING CRAWLER.
2020-08-26T04:36:18.571Z INFO  CheerioCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.7,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2020-08-26T04:36:19.151Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":1,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:19.152Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:19.152Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:19.153Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:19.153Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:19.153Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:22.450Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":2,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:22.451Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:22.451Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:22.451Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:22.452Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:22.452Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:26.165Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":3,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:26.166Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:26.166Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:26.167Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:26.168Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:26.168Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:29.776Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":4,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:29.782Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:29.783Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:29.784Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:29.785Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:29.786Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:33.393Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":5,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:33.394Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:33.395Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:33.397Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:33.400Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:33.405Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:37.034Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":6,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:37.034Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:37.035Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:37.035Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:37.036Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:37.036Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:40.268Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":7,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:40.272Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:40.272Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:40.273Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:40.273Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:40.273Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:43.451Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":8,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:43.454Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:43.455Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:43.455Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:43.455Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:43.455Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:47.103Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":9,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:47.103Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:47.104Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:47.104Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:47.105Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:47.105Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:50.754Z ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200003482/dresses.html","retryCount":10,"id":"lT6p7QLVC7A6JDS"}
2020-08-26T04:36:50.754Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:50.755Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:50.755Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:50.755Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:50.756Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:54.062Z ERROR CheerioCrawler: Request failed and reached maximum retries {"id":"lT6p7QLVC7A6JDS","url":"https://www.aliexpress.com/category/200003482/dresses.html","method":"GET","uniqueKey":"https://www.aliexpress.com/category/200003482/dresses.html"}
2020-08-26T04:36:54.062Z   Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html
2020-08-26T04:36:54.063Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T04:36:54.063Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T04:36:54.064Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T04:36:54.064Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
2020-08-26T04:36:54.130Z INFO  CheerioCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
2020-08-26T04:36:54.131Z INFO  CheerioCrawler: Final request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":1,"retryHistogram":[null,null,null,null,null,null,null,null,null,null,1]}
2020-08-26T04:36:54.131Z INFO  PHASE -- ACTOR FINISHED.
2020-08-26T04:36:55.231Z INFO  PHASE -- ACTOR FINISHED.

**Comment by metalwarrior665** [comment]
Hello,

It tells you what was wrong `Error: We got blocked by target on https://www.aliexpress.com/category/200003482/dresses.html` but the error should be more visible. What proxy are you using?

**Comment by jongming** [comment]
Do you mean the proxy configuration? Used default 'none'
"proxy": {
    "useApifyProxy": false
  },

**Comment by metalwarrior665** [comment]
Aliexpress is pretty harsh in blocking so you don't have much chance without IP rotation. If you have access to Apify proxy, try

```
"proxy": {
"useApifyProxy": true
},
```

**Comment by jongming** [comment]
Just tried setting useApifyProxy to true but got the same error message: 

ERROR CheerioCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.aliexpress.com/category/200000097/bracelets-bangles.html","retryCount":1,"id":"jPhWmwhS8Jl876d"}
2020-08-26T12:45:17.252Z   Error: We got blocked by target on https://www.aliexpress.com/category/200000097/bracelets-bangles.html
2020-08-26T12:45:17.253Z       at CheerioCrawler.handlePageFunction (/usr/src/app/src/main.js:83:23)
2020-08-26T12:45:17.253Z       at CheerioCrawler._handleRequestFunction (/usr/src/app/node_modules/apify/build/crawlers/cheerio_crawler.js:451:49)
2020-08-26T12:45:17.253Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-26T12:45:17.254Z       at async /usr/src/app/node_modules/apify/build/utils.js:362:26
